### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by nolleto** [fhelwanger/bayesjs#5]
I think would be awesome to have some CI to run:
- `yarn lint` 
- `yarn test`
- `yarn build`

**Comment by fhelwanger** [comment]
Sorry, I don't get it. Do you mean a way to run those 3 commands together?

**Comment by nolleto** [comment]
Oohh, I typed `CI` wrong 😓 

Some continuous integration, like [travis](https://travis-ci.org/).

**Comment by fhelwanger** [comment]
Ah ok, makes sense 😄 

Yeah it'd be nice. 👍
